CREATE SCHEMA IF NOT EXISTS schema_authentication AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS schema_email AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS schema_salary AUTHORIZATION postgres;